project: "365bot"

genre:
  - product_name: "AGA完全ロードマップPDF"
    price: 1480
    expected_cvr: 0.05
    notify_user_ids: ["<あなたのLINEユーザーID>"]
  - product_name: "初回相談デポジット"
    price: 3000
    expected_cvr: 0.12
    notify_user_ids: ["<あなたのLINEユーザーID>"]

stripe:
  aga_payment_link: "https://buy.stripe.com/test_5kQve0zAG0T8omqYmcFk00"
  consult_payment_link: "https://buy.stripe.com/test_9864qy23E79j9WyYmcFk01"
