project: "365bot"

genre:
  - product_name: "AGA完全ロードマップPDF"
    price: 1480
    expected_cvr: 0.05
    notify_user_ids: ["<あなたのLINEユーザーID>"]
  - product_name: "初回相談デポジット"
    price: 3000
    expected_cvr: 0.12
    notify_user_ids: ["<あなたのLINEユーザーID>"]
