name: 365bot

on:
  schedule:
    # 毎時10分間隔で実行
    - cron: '*/10 * * * *'
  workflow_dispatch:
    # 手動実行を許可
    inputs: {}

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      LINE_BOT_TOKEN: ${{ secrets.LINE_BOT_TOKEN }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run bot script
        run: |
          python main.py
