name: create-stripe-links
on:
  workflow_dispatch:
    inputs:
      aga_price:
        description: 'AGA PDF price in JPY (default 1480)'
        default: '1480'
      consult_price:
        description: 'Consultation deposit price in JPY (default 3000)'
        default: '3000'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install stripe@^15
      - name: Create Stripe payment links
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          AGA_PRICE: ${{ github.event.inputs.aga_price }}
          CONSULT_PRICE: ${{ github.event.inputs.consult_price }}
          THANKS_URL: "https://<your-worker-url>/thanks"
        run: node scripts/create_stripe_links.js
