name: create-stripe-links

on:
  workflow_dispatch:
    inputs:
      aga_price:
        description: 'AGA PDF price in JPY (optional, default 1480)'
        required: false
        default: '1480'
      consult_price:
        description: 'Consultation deposit price in JPY (optional, default 3000)'
        required: false
        default: '3000'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install stripe module
        run: |
          npm init -y
          npm install stripe@^15
      - name: Create Stripe payment links
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          AGA_PRICE: ${{ github.event.inputs.aga_price }}
          CONSULT_PRICE: ${{ github.event.inputs.consult_price }}
          THANKS_URL: "https://lucky-unit-4eb8.2sqycxngzh.workers.dev/thanks"
        run: node scripts/create_stripe_links.js
