name: test-lead

on:
  workflow_dispatch:
    inputs:
      product:
        description: product_name in config.yaml
        required: true
        default: "AGA完全ロードマップPDF"
      external_id:
        description: unique lead id
        required: true
        default: "TEST-001"
      email:
        description: buyer email
        required: true
        default: "test@example.com"
      phone:
        description: phone
        required: false
        default: ""
      name:
        description: name
        required: false
        default: "テスト顧客"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      LINE_BOT_TOKEN: ${{ secrets.LINE_BOT_TOKEN }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      FORM_EXTERNAL_ID: ${{ github.event.inputs.external_id }}
      FORM_EMAIL: ${{ github.event.inputs.email }}
      FORM_PHONE: ${{ github.event.inputs.phone }}
      FORM_PRODUCT: ${{ github.event.inputs.product }}
      FORM_NAME: ${{ github.event.inputs.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml tenacity stripe
      - name: Run 365bot (register lead + KPI + notifications)
        run: python main.py
